// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: rpcpb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemService_Login_FullMethodName              = "/pb.system_service/Login"
	SystemService_Logout_FullMethodName             = "/pb.system_service/Logout"
	SystemService_CheckToken_FullMethodName         = "/pb.system_service/CheckToken"
	SystemService_GetUserRoles_FullMethodName       = "/pb.system_service/GetUserRoles"
	SystemService_GetUserPermissions_FullMethodName = "/pb.system_service/GetUserPermissions"
	SystemService_GetUserMenu_FullMethodName        = "/pb.system_service/GetUserMenu"
	SystemService_GetRoleMenu_FullMethodName        = "/pb.system_service/GetRoleMenu"
	SystemService_UserList_FullMethodName           = "/pb.system_service/UserList"
)

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	// 用户登陆
	Login(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 用户退出登陆
	Logout(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 验证token
	CheckToken(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 获取用户角色列表
	GetUserRoles(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 查询用户权限列表
	GetUserPermissions(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 查询用户菜单列表
	GetUserMenu(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 查询角色菜单列表
	GetRoleMenu(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
	// 查询角色下的用户列表
	UserList(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) Login(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) Logout(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CheckToken(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_CheckToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUserRoles(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_GetUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUserPermissions(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_GetUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUserMenu(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_GetUserMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetRoleMenu(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_GetRoleMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UserList(ctx context.Context, in *RpcParam, opts ...grpc.CallOption) (*RpcResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcResp)
	err := c.cc.Invoke(ctx, SystemService_UserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations should embed UnimplementedSystemServiceServer
// for forward compatibility.
type SystemServiceServer interface {
	// 用户登陆
	Login(context.Context, *RpcParam) (*RpcResp, error)
	// 用户退出登陆
	Logout(context.Context, *RpcParam) (*RpcResp, error)
	// 验证token
	CheckToken(context.Context, *RpcParam) (*RpcResp, error)
	// 获取用户角色列表
	GetUserRoles(context.Context, *RpcParam) (*RpcResp, error)
	// 查询用户权限列表
	GetUserPermissions(context.Context, *RpcParam) (*RpcResp, error)
	// 查询用户菜单列表
	GetUserMenu(context.Context, *RpcParam) (*RpcResp, error)
	// 查询角色菜单列表
	GetRoleMenu(context.Context, *RpcParam) (*RpcResp, error)
	// 查询角色下的用户列表
	UserList(context.Context, *RpcParam) (*RpcResp, error)
}

// UnimplementedSystemServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemServiceServer struct{}

func (UnimplementedSystemServiceServer) Login(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSystemServiceServer) Logout(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedSystemServiceServer) CheckToken(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}
func (UnimplementedSystemServiceServer) GetUserRoles(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRoles not implemented")
}
func (UnimplementedSystemServiceServer) GetUserPermissions(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedSystemServiceServer) GetUserMenu(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMenu not implemented")
}
func (UnimplementedSystemServiceServer) GetRoleMenu(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleMenu not implemented")
}
func (UnimplementedSystemServiceServer) UserList(context.Context, *RpcParam) (*RpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedSystemServiceServer) testEmbeddedByValue() {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	// If the following call pancis, it indicates UnimplementedSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Login(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Logout(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_CheckToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CheckToken(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUserRoles(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUserPermissions(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUserMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUserMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetUserMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUserMenu(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetRoleMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetRoleMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_GetRoleMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetRoleMenu(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemService_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UserList(ctx, req.(*RpcParam))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.system_service",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SystemService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _SystemService_Logout_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _SystemService_CheckToken_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _SystemService_GetUserRoles_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _SystemService_GetUserPermissions_Handler,
		},
		{
			MethodName: "GetUserMenu",
			Handler:    _SystemService_GetUserMenu_Handler,
		},
		{
			MethodName: "GetRoleMenu",
			Handler:    _SystemService_GetRoleMenu_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _SystemService_UserList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcpb.proto",
}
