// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpcpb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHeader) Reset() {
	*x = RpcHeader{}
	mi := &file_rpcpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHeader) ProtoMessage() {}

func (x *RpcHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHeader.ProtoReflect.Descriptor instead.
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHeader) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RpcHeader) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RpcParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcParam) Reset() {
	*x = RpcParam{}
	mi := &file_rpcpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcParam) ProtoMessage() {}

func (x *RpcParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcParam.ProtoReflect.Descriptor instead.
func (*RpcParam) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{1}
}

func (x *RpcParam) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *RpcParam) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RpcResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResp) Reset() {
	*x = RpcResp{}
	mi := &file_rpcpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResp) ProtoMessage() {}

func (x *RpcResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResp.ProtoReflect.Descriptor instead.
func (*RpcResp) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RpcResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` //用户名
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                 //密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_rpcpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserRoleMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //角色ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleMenuReq) Reset() {
	*x = UserRoleMenuReq{}
	mi := &file_rpcpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleMenuReq) ProtoMessage() {}

func (x *UserRoleMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleMenuReq.ProtoReflect.Descriptor instead.
func (*UserRoleMenuReq) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{4}
}

func (x *UserRoleMenuReq) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UserRoleMenuReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UserListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` //角色ID
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	LoginName     string                 `protobuf:"bytes,4,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	JobNum        int64                  `protobuf:"varint,5,opt,name=job_num,json=jobNum,proto3" json:"job_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	mi := &file_rpcpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{5}
}

func (x *UserListReq) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UserListReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserListReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserListReq) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *UserListReq) GetJobNum() int64 {
	if x != nil {
		return x.JobNum
	}
	return 0
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	List          []*AdminUserInfo       `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_rpcpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{6}
}

func (x *UserListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserListResp) GetList() []*AdminUserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RpcHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         //用户ID
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`    //姓名
	UserPhone     string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"` //手机号
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"` //邮箱
	NickName      string                 `protobuf:"bytes,6,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`    //昵称
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`                        //头像
	Sex           int32                  `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty"`                             //性别
	Roles         []*AdminRole           `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`                          //角色ID列表
	Permissions   []string               `protobuf:"bytes,10,rep,name=permissions,proto3" json:"permissions,omitempty"`             //权限字符列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_rpcpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{7}
}

func (x *AdminUser) GetHeader() *RpcHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AdminUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminUser) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *AdminUser) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AdminUser) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AdminUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUser) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *AdminUser) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminUser) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AdminUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         //用户ID
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`    //姓名
	UserPhone     string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"` //手机号
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"` //邮箱
	NickName      string                 `protobuf:"bytes,6,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`    //昵称
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`                        //头像
	Sex           int32                  `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty"`                             //性别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserInfo) Reset() {
	*x = AdminUserInfo{}
	mi := &file_rpcpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserInfo) ProtoMessage() {}

func (x *AdminUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserInfo.ProtoReflect.Descriptor instead.
func (*AdminUserInfo) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{8}
}

func (x *AdminUserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminUserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AdminUserInfo) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *AdminUserInfo) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AdminUserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *AdminUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AdminUserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

type AdminRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`      //角色ID
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` //角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_rpcpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{9}
}

func (x *AdminRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type MenuTreeModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameEn        string                 `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Redirect      string                 `protobuf:"bytes,7,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Component     string                 `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
	Query         string                 `protobuf:"bytes,9,opt,name=query,proto3" json:"query,omitempty"`
	AlwaysShow    bool                   `protobuf:"varint,10,opt,name=always_show,json=alwaysShow,proto3" json:"always_show,omitempty"`
	Children      []*MenuTreeModel       `protobuf:"bytes,12,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeModel) Reset() {
	*x = MenuTreeModel{}
	mi := &file_rpcpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeModel) ProtoMessage() {}

func (x *MenuTreeModel) ProtoReflect() protoreflect.Message {
	mi := &file_rpcpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeModel.ProtoReflect.Descriptor instead.
func (*MenuTreeModel) Descriptor() ([]byte, []int) {
	return file_rpcpb_proto_rawDescGZIP(), []int{10}
}

func (x *MenuTreeModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuTreeModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuTreeModel) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *MenuTreeModel) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuTreeModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuTreeModel) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MenuTreeModel) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *MenuTreeModel) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuTreeModel) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MenuTreeModel) GetAlwaysShow() bool {
	if x != nil {
		return x.AlwaysShow
	}
	return false
}

func (x *MenuTreeModel) GetChildren() []*MenuTreeModel {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_rpcpb_proto protoreflect.FileDescriptor

const file_rpcpb_proto_rawDesc = "" +
	"\n" +
	"\vrpcpb.proto\x12\x02pb\"5\n" +
	"\tRpcHeader\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"8\n" +
	"\trpc_param\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"L\n" +
	"\brpc_resp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"j\n" +
	"\bLoginReq\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.RpcHeaderR\x06header\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"Q\n" +
	"\x0fUserRoleMenuReq\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.RpcHeaderR\x06header\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\"\xa2\x01\n" +
	"\vUserListReq\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.RpcHeaderR\x06header\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"login_name\x18\x04 \x01(\tR\tloginName\x12\x17\n" +
	"\ajob_num\x18\x05 \x01(\x03R\x06jobNum\"K\n" +
	"\fUserListResp\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12%\n" +
	"\x04list\x18\x04 \x03(\v2\x11.pb.AdminUserInfoR\x04list\"\xb4\x02\n" +
	"\tAdminUser\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.pb.RpcHeaderR\x06header\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tnick_name\x18\x06 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\b \x01(\x05R\x03sex\x12#\n" +
	"\x05roles\x18\t \x03(\v2\r.pb.AdminRoleR\x05roles\x12 \n" +
	"\vpermissions\x18\n" +
	" \x03(\tR\vpermissions\"\xca\x01\n" +
	"\rAdminUserInfo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tnick_name\x18\x06 \x01(\tR\bnickName\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12\x10\n" +
	"\x03sex\x18\b \x01(\x05R\x03sex\"A\n" +
	"\tAdminRole\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\"\xac\x02\n" +
	"\rMenuTreeModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aname_en\x18\x03 \x01(\tR\x06nameEn\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\x12\x1a\n" +
	"\bredirect\x18\a \x01(\tR\bredirect\x12\x1c\n" +
	"\tcomponent\x18\b \x01(\tR\tcomponent\x12\x14\n" +
	"\x05query\x18\t \x01(\tR\x05query\x12\x1f\n" +
	"\valways_show\x18\n" +
	" \x01(\bR\n" +
	"alwaysShow\x12-\n" +
	"\bchildren\x18\f \x03(\v2\x11.pb.MenuTreeModelR\bchildren2\xf9\x02\n" +
	"\x0esystem_service\x12&\n" +
	"\x05Login\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12'\n" +
	"\x06Logout\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12+\n" +
	"\n" +
	"CheckToken\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12-\n" +
	"\fGetUserRoles\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x123\n" +
	"\x12GetUserPermissions\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12,\n" +
	"\vGetUserMenu\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12,\n" +
	"\vGetRoleMenu\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00\x12)\n" +
	"\bUserList\x12\r.pb.rpc_param\x1a\f.pb.rpc_resp\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_rpcpb_proto_rawDescOnce sync.Once
	file_rpcpb_proto_rawDescData []byte
)

func file_rpcpb_proto_rawDescGZIP() []byte {
	file_rpcpb_proto_rawDescOnce.Do(func() {
		file_rpcpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpcpb_proto_rawDesc), len(file_rpcpb_proto_rawDesc)))
	})
	return file_rpcpb_proto_rawDescData
}

var file_rpcpb_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpcpb_proto_goTypes = []any{
	(*RpcHeader)(nil),       // 0: pb.RpcHeader
	(*RpcParam)(nil),        // 1: pb.rpc_param
	(*RpcResp)(nil),         // 2: pb.rpc_resp
	(*LoginReq)(nil),        // 3: pb.LoginReq
	(*UserRoleMenuReq)(nil), // 4: pb.UserRoleMenuReq
	(*UserListReq)(nil),     // 5: pb.UserListReq
	(*UserListResp)(nil),    // 6: pb.UserListResp
	(*AdminUser)(nil),       // 7: pb.AdminUser
	(*AdminUserInfo)(nil),   // 8: pb.AdminUserInfo
	(*AdminRole)(nil),       // 9: pb.AdminRole
	(*MenuTreeModel)(nil),   // 10: pb.MenuTreeModel
}
var file_rpcpb_proto_depIdxs = []int32{
	0,  // 0: pb.LoginReq.header:type_name -> pb.RpcHeader
	0,  // 1: pb.UserRoleMenuReq.header:type_name -> pb.RpcHeader
	0,  // 2: pb.UserListReq.header:type_name -> pb.RpcHeader
	8,  // 3: pb.UserListResp.list:type_name -> pb.AdminUserInfo
	0,  // 4: pb.AdminUser.header:type_name -> pb.RpcHeader
	9,  // 5: pb.AdminUser.roles:type_name -> pb.AdminRole
	10, // 6: pb.MenuTreeModel.children:type_name -> pb.MenuTreeModel
	1,  // 7: pb.system_service.Login:input_type -> pb.rpc_param
	1,  // 8: pb.system_service.Logout:input_type -> pb.rpc_param
	1,  // 9: pb.system_service.CheckToken:input_type -> pb.rpc_param
	1,  // 10: pb.system_service.GetUserRoles:input_type -> pb.rpc_param
	1,  // 11: pb.system_service.GetUserPermissions:input_type -> pb.rpc_param
	1,  // 12: pb.system_service.GetUserMenu:input_type -> pb.rpc_param
	1,  // 13: pb.system_service.GetRoleMenu:input_type -> pb.rpc_param
	1,  // 14: pb.system_service.UserList:input_type -> pb.rpc_param
	2,  // 15: pb.system_service.Login:output_type -> pb.rpc_resp
	2,  // 16: pb.system_service.Logout:output_type -> pb.rpc_resp
	2,  // 17: pb.system_service.CheckToken:output_type -> pb.rpc_resp
	2,  // 18: pb.system_service.GetUserRoles:output_type -> pb.rpc_resp
	2,  // 19: pb.system_service.GetUserPermissions:output_type -> pb.rpc_resp
	2,  // 20: pb.system_service.GetUserMenu:output_type -> pb.rpc_resp
	2,  // 21: pb.system_service.GetRoleMenu:output_type -> pb.rpc_resp
	2,  // 22: pb.system_service.UserList:output_type -> pb.rpc_resp
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpcpb_proto_init() }
func file_rpcpb_proto_init() {
	if File_rpcpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_proto_rawDesc), len(file_rpcpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_proto_goTypes,
		DependencyIndexes: file_rpcpb_proto_depIdxs,
		MessageInfos:      file_rpcpb_proto_msgTypes,
	}.Build()
	File_rpcpb_proto = out.File
	file_rpcpb_proto_goTypes = nil
	file_rpcpb_proto_depIdxs = nil
}
